[[m-mode-modification]]
== "Smpmpdeleg" Extension for Sharing Hardware Resources between PMP and SPMP

Given that the PMP and SPMP registers have a similar layout of address/config registers and the same address matching logic, reusing registers and comparators between PMP and SPMP is beneficial to save hardware resources.
This chapter presents the `Smpmpdeleg` extension, a resource sharing mechanism enabling dynamic reallocation of hardware resources between PMP and SPMP.
This extension is mandatory.

[[PMP_Entry_Sharing]]
=== Resource Sharing between PMP and SPMP

The `Smpmpdeleg` extension enables delegation of PMP entries for S-level use.
These delegated entries are referred to as S-level PMP (SPMP) entries.

A 32-bit M-mode CSR called `mpmpdeleg` is introduced to control the sharing of PMP entries between PMP and SPMP.
The layout of `mpmpdeleg` is shown in <<mpmpdeleg_format_32>> and <<mpmpdeleg_format_64>>:

. The `pmpnum` field is a WARL field specifying the index of the lowest PMP entry delegated to S-level. 
All PMP entries with an index greater than or equal to `pmpnum` are delegated as SPMP entries.
. If `pmpnum` is written with a value greater than the number of implemented PMP entries, the field will read back as the number of implemented PMP entries.
. When `pmpnum` is set to zero, all PMP entries are delegated; when it is set to the number of implemented PMP entries, no entries are delegated.
. Unless `pmpnum` is hardwired, its reset value equals the number of implemented PMP entries.


[[mpmpdeleg_format_rv64]]
.mpmpdeleg CSR format.
include::images/bytefield/mpmpdeleg_format_rv64.adoc[]



[NOTE]
====
The `mpmpdeleg.pmpnum` is WARL, and allows an implementation to hardwire the PMP/SPMP split if desired.
====

*Addressing:*

Both PMP and SPMP entries will be supported contiguously.
The PMP entries begin with the lowest CSR number, while the SPMP entries begin with `pmpnum`.
For instance, given an implementation with a total of 64 PMP entries, if `pmpnum` is set to 16 during runtime,
`PMP entry[0]` to `PMP entry[15]` would map to `PMP[0]` to `PMP[15]`.
The remaining entries, `PMP entry[16]` to `PMP entry[63]`, would be mapped as `SPMP[16]` to `SPMP[63]`.
A read of an out-of-index PMP entry (e.g., `PMP[16]` or `SPMP[15]`) will return 0, and a write to such a PMP entry will be ignored.


[NOTE]
====
Software that uses SPMP should start with `SPMP[pmpnum]`.
====

*Re-configuration:*

. M-mode software can re-configure the allocation of entries for PMP vs. SPMP by modifying the `mpmpdeleg` CSR.
+
. The `pmpnum` must be set to a value larger than the index of any *locked* PMP entry.
For example, if `PMP[7]` is locked, `pmpnum` must be no less than 8.

