== Machine-level Modification

Given that PMP and SPMP have similar layout of address/config registers and the same address matching logic.
Reusing registers and comparators between PMP and SPMP may be benefitial (in some cases) to save hardware resources.
This chapter introduces the resource sharing mechanism that can support dynamic reallocation of hardware resource between PMP and SPMP.

[[PMP_Resource_Sharing]]
=== Resource Sharing between PMP and SPMP

Implementations should consider PMP/SPMP entries as a resource pool (called PMP_Resource).
Specifically, each PMP_Resource consists of an address CSR, a configuration CSR, and associated micro-architecture state.
A new M-mode CSR called `mpmpdeleg` is introduced to control the sharing of PMP_Resource between PMP and SPMP.

In the following description, we will refer to the PMP/SPMP from the hardware perspective as `PMP_Resource`, and the PMP/SPMP from the software perspective as `entry`.


The 16-bit CSR shown in <<mpmpdeleg_format>> has one `pmpnum` field:

. `pmpnum` is 7-bit, allowing a value of 0--64 to specify the number of PMP entries.
. Any PMP_Resource greater than or equal to the `pmpnum` is delegated to S-mode (SPMP). The lower numbered PMP_Resource are left for M-mode (PMP).
. M-mode could set `pmpnum>=64` (the number of implemented PMP_Resource), to reserve all resources for PMP.
. M-mode could set `pmpnum=0` to delegate all PMP_Resource to SPMP. 
. The reset value of `pmpnum` is `0b100_0000`.
. The `pmpnum` is locked when `mseccfg.MML` is set (Please refer to the `Smepmp` extension specification for details on `mseccfg.MML`).


[[mpmpdeleg_format]]
.mpmpdeleg CSR format.
include::images/bytefield/mpmpdeleg_format.adoc[]

*Constraints:*

. With RV32, the values of `pmpnum`, can only be a multiple of 4; with RV64, it can only be a multiple of 8. This design avoids sharing the same configuration CSR between S-mode and M-mode.
. The `pmpnum` is a WARL field. Illegal writes (e.g., values that are not multiples of 4 (RV32) or 8 (RV64)) should be ignored.
. If the SPMP entry with lowest CSR number is configured with TOR address-matching mode (i.e., `spmp[0]cfg.A == TOR`), zero is used for the lower bound.


[NOTE]
====
The `mpmpdeleg` CSR is WARL, and allows an implementation to hardwire the PMP/SPMP split if desired.

To reduce context-switch overhead, S-mode software should evaluate the number of SPMP rules each S-mode context needs and set `mpmpdeleg.pmpnum` accordingly.
====

*Addressing:*

Both PMP and SPMP entries will be supported contiguously.
The PMP entries begin with the lowest CSR number, while the SPMP entries begin with `mpmpdeleg.pmpnum`.
For instance, given an implementation with a total of 64 PMP Resource entries, if `mpmpdeleg.pmpnum` is set to 16 during runtime,
`PMPResource[0]` to `PMPResource[15]` would map to `PMP[0]` to `PMP[15]`.
The remaining entries, `PMPResource[16]` to `PMPResource[63]`, would be mapped as `SPMP[0]` to `SPMP[47]`.

From a software perspective, the SPMP entries start from `SPMP[0]`.
The available number of SPMP entries can be discovered by writing to and reading from the SPMP CSRs.


*Re-configuration:*

M-mode software can re-configure the entries for PMP and SPMP by modifying the `mpmpdeleg` CSR.
A re-configuration involving locked PMP entry will leave `mpmpdeleg` unchanged.

[[m_mode_indirect_access]]
=== Access Method of PMP_Resource

*Indirect CSR access*: `PMP_Resource` CSRs can be accessed indirectly from M-mode.
Each combination of `miselect` and `mireg` represents an access to the corresponding `PMP_Resource` CSR.

There is no ordering guarantee between writes to different `PMP_Resource` CSRs via indirect access, except when explicitly executing an `SFENCE.VMA` instruction with `rs1=x0` and `rs2=x0`.

The `spmp[i]cfg.L` bit can only be reset when accessing in M-mode via `miselect`.

The `miselect` has the same view of `siselect`.
For example, given an implementation with 64 PMP_Resource, where 48 entries are delegated to S-mode.
S-mode can access `SPMP[0..47]` via `siselect#0..47`.
M-mode can access `SPMP[0..47]` via `siselect#0..47` or `miselect#0..47`.
In such a case, both privileged mode attempts to access `SPMP[i]`, where `i >= 64 - mpmpdeleg.pmpnum`, will raise an illegal instruction exception.


[cols="^1,^2",stripes=even, options="header"]
|===
|`miselect` number| indirect CSR access of `mireg`
|`miselect#0`|`mireg` -> `spmpaddr[0]`, `mireg2` -> `spmp[0]cfg`
|`miselect#1`|`mireg` -> `spmpaddr[1]`, `mireg2` -> `spmp[1]cfg`
|    ...     |    ...     
|`miselect#63`|`mireg` -> `spmpaddr[63]`, `mireg2` -> `spmp[63]cfg`
|===
