[[m-mode-modification]]
== Machine Mode Modification

Given that PMP and SPMP have similar layout of address/config registers and the same address matching logic.
Reusing registers and comparators between PMP and SPMP may be beneficial (in some cases) to save hardware resources.
This chapter introduces the resource sharing mechanism that can support reallocation of hardware resource between PMP and SPMP.

[[PMP_Resource_Sharing]]
=== Resource Sharing between PMP and SPMP

Implementations should consider PMP/SPMP entries as a resource pool (called PMP_Resource).
Specifically, each PMP_Resource consists of an address CSR, a configuration CSR, and associated micro-architecture state.
A new M-mode CSR called `mpmpdeleg` is introduced to control the sharing of PMP_Resource between PMP and SPMP.

In the following description, we will refer to the PMP/SPMP from the hardware perspective as `PMP_Resource`, and the PMP/SPMP from the software perspective as `entry`.


The 16-bit CSR shown in <<mpmpdeleg_format_32>> and <<mpmpdeleg_format_rv64>> has one `pmpnum` field:

. `pmpnum` is 7-bit, allowing a value of 0--64 to specify the number of PMP entries. In RV32, the values of `pmpnum`, can only be a multiple of 4 (the lowest 2 bits are read-only 0); In RV64, it can only be a multiple of 8 (the lowest 3 bits are read-only 0). This design avoids sharing the same configuration CSR between S-mode and M-mode.
. Any PMP_Resource greater than or equal to the `pmpnum` is delegated to S-mode (SPMP). The lower numbered PMP_Resource are left for M-mode (PMP).
. M-mode could set `pmpnum>=64` (the number of implemented PMP_Resource), to reserve all resources for PMP.
. M-mode could set `pmpnum=0` to delegate all PMP_Resource to SPMP. 
. For implementations that do not hardwire the `pmpnum`, the reset value of `pmpnum` is `0b100_0000` (no delegation).
. The `pmpnum` is locked when `mseccfg.MML` is set (Please refer to the `Smepmp` extension specification for details on `mseccfg.MML`).
. If the SPMP entry with lowest CSR number is configured with TOR address-matching mode (i.e., `spmp[0]cfg.A == TOR`), zero is used for the lower bound.

An S-mode read-only shadow of `mpmpdeleg` CSR, called `spmpdeleg`, is provided to S-mode software to obtain the `pmpnum` value without invoking an SBI call.



[[mpmpdeleg_format_32]]
.mpmpdeleg CSR format, RV32.
include::images/bytefield/mpmpdeleg_format_rv32.adoc[]

[[mpmpdeleg_format_rv64]]
.mpmpdeleg CSR format, RV64.
include::images/bytefield/mpmpdeleg_format_rv64.adoc[]



[NOTE]
====
The `mpmpdeleg` CSR is WARL, and allows an implementation to hardwire the PMP/SPMP split if desired.
====

*Addressing:*

Both PMP and SPMP entries will be supported contiguously.
The PMP entries begin with the lowest CSR number, while the SPMP entries begin with `pmpnum`.
For instance, given an implementation with a total of 64 PMP Resource entries, if `pmpnum` is set to 16 during runtime,
`PMPResource[0]` to `PMPResource[15]` would map to `PMP[0]` to `PMP[15]`.
The remaining entries, `PMPResource[16]` to `PMPResource[63]`, would be mapped as `SPMP[16]` to `SPMP[63]`.
A read of an out-of-index PMPResource (e.g., `PMP[16]` or `SPMP[15]`) will return 0, and a write to such a PMPResource will be ignored.

[NOTE]
====
Software that uses SPMP should start with `SPMP[pmpnum]`.

// S-mode software can use `spmpdeleg` to obtain the `pmpnum` value without invoking an SBI call.
====

*Re-configuration:*

. M-mode software can re-configure the allocation of entries for PMP vs. SPMP by modifying the `mpmpdeleg` CSR.
+
. The behavior that attempts to modify `mpmpdeleg`, which delegates a locked PMP entry to an SPMP entry, is *UNDEFINED*.

