[[S-mode_Physical_Memory_Protection]]
== S-mode Physical Memory Protection (SPMP)

An optional RISC-V S-mode Physical Memory Protection (SPMP) provides per-hart supervisor-mode control registers to allow physical memory access privileges (read, write, execute) to be specified for each physical memory region.
// The SPMP is also applied to data accesses in M-mode when the MPRV bit in mstatus is set and the MPP field in mstatus contains S or U.

// Like PMP, the granularity of SPMP access control settings is platform-specific and, within a platform, may vary by physical memory region. However, the standard SPMP encoding support regions as small as four bytes. 

If PMP/ePMP is implemented, accesses succeed only if both PMP/ePMP and SPMP permission checks pass.
The implementation can perform SPMP checks in parallel with PMA and PMP.
The SPMP exception reports have higher priority than PMP or PMA exceptions (i.e., if the access violates both SPMP and PMP/PMA, the SPMP exception will be reported).

SPMP checks will be applied to all accesses whose effective privilege mode is S or U, including instruction fetches and data accesses in S and U mode, 
and data accesses in M-mode when the MPRV bit in mstatus is set and the MPP field in mstatus contains S or U.

SPMP registers can always be modified by M-mode and S-mode software.

SPMP can grant permissions to U-mode, which has none by default. 
SPMP can also revoke permissions from S-mode.

=== Requirements

. S mode should be implemented
+
. The `sstatus.SUM` (permit Supervisor User Memory access) bit must be *writeable*.
+
[NOTE]
====
The Privileged Architecture specification states the following
[quote, Supervisor-Level ISA, Version 1.13 >> "Memory Privilege in `sstatus` Register"]
____
`SUM` has no effect when page-based virtual memory is not in effect, nor when executing in U-mode.
`SUM` is read-only 0 if `satp.MODE` is read-only 0.
____
In SPMP, this bit modifies the privilege with which S-mode loads and stores access to physical
memory, hence the need to make it writeable.
====
. The `sstatus.MXR` (Make eXecutable Readable) bit must be *writeable*.
+
[NOTE]
====
The Privileged Architecture specification states that
[quote, Machine-Level ISA, Version 1.13 >> "Memory Privilege in `mstatus` Register"]
____
`MXR` has no effect when page-based virtual memory is not in effect.
____
In SPMP, the `MXR` bit modifies the privilege with which loads access physical memory.
Its semantics are consistent with those of the Machine-Level ISA.

In SPMP, this bit is made writeable to support M-mode emulation handlers where instructions are read
with `MXR=1` and `MPRV=1`.
====

=== S-mode Physical Memory Protection CSRs

Like PMP, SPMP entries are described by an 8-bit configuration register and one XLEN-bit address register. Some SPMP settings additionally use the address register associated with the preceding SPMP entry. Up to 64 SPMP entries are supported.

The SPMP configuration registers are packed into CSRs the same way as PMP. For RV32, 16 CSRs, `spmpcfg0`-`spmpcfg15`, hold the configurations `spmp0cfg`-`spmp63cfg` for the 64 SPMP entries.
For RV64, even numbered CSRs (i.e., `spmpcfg0`, `spmpcfg2`, ..., `spmpcfg14`) hold the configurations for the 64 SPMP entries; odd numbered CSRs (e.g., `spmpcfg1`) are illegal.
<<spmpcfg-rv32>> and <<spmpcfg-rv64>> demonstrate the first 16 entries of SPMP. The layout of the rest of the entries is identical.

[NOTE]
====
The terms, entry and rule, are similar to ePMP.

The implementation must decode all SPMP CSRs, and it can modify the number of *writable SPMP entries* while the remaining SPMP CSRs are read-only zero.

The lowest-numbered SPMP entries must be implemented first.
====
[[spmpcfg-rv32]]
.RV32 SPMP configuration CSR layout.
include::images/bytefield/spmp-rv32.adoc[]

[[spmpcfg-rv64]]
.RV64 SPMP configuration CSR layout.
include::images/bytefield/spmp-rv64.adoc[]

The SPMP address registers are CSRs named `spmpaddr0`-`spmpaddr63`.
Each SPMP address register encodes bits 33-2 of 34-bit physical address for RV32, as shown in <<spmpaddr-rv32>>.
For RV64, each SPMP address encodes bits 55-2 of a 56-bit physical address, as shown in <<spmpaddr-rv64>>.
Fewer address bits may be implemented for specific reasons, e.g., systems with smaller physical address space.
The number of address bits should be the same for all *writable SPMP entries*.
Implemented address bits must extend to the LSB format, except as otherwise permitted by granularity rules. See the Privileged Architecture specification, Section 3.7: Physical Memory Protection, Address Matching.

[[spmpaddr-rv32]]
.SPMP address register format, RV32.
include::images/bytefield/spmpaddr-rv32.adoc[]

[[spmpaddr-rv64]]
.SPMP address register format, RV64.
include::images/bytefield/spmpaddr-rv64.adoc[]

The layout of SPMP configuration registers is the same as PMP configuration registers, as shown in <<spmpcfg>>. The register is WARL.
The rules and encodings for permission are explained in section 2.4, which resembles the encoding of ePMP (except SPMP does not use locked rules).

. The S bit marks a rule as *S-mode-only* when set and *U-mode-only* when unset.

. Bit 5 and 6 are reserved for future use.

. The A field will be described in the following sections (2.3).

. The R/W/X bits control read, write, and instruction execution permissions.

[[spmpcfg]]
.SPMP configuration register format.
include::images/bytefield/spmpcfg.adoc[]


=== Encoding of Permissions


SPMP has three kinds of rules: *S-mode-only*, *U-mode-only* and *Shared-Region* rules.
// The S bit marks a rule as *S-mode-only* when set and *U-mode-only* when unset.
// The encoding `spmpcfg.RW=01` encodes a Shared-Region and `spmpcfg.SRWX=1000` is reserved for future standard use.

. An *S-mode-only* rule is *enforced* on Supervisor mode and *denied* on User mode.
+
. A *U-mode-only* rule is *enforced* on User modes and is either *denied* or *enforced* on Supervisor mode depending on the value of `sstatus.SUM` bit:
+
* If `sstatus.SUM` is set, a U-mode-only rule is enforced on Supervisor mode, yet not be executable. This ensures the Supervisor Memory Execution Prevention (SMEP).
+
* If `sstatus.SUM` is unset, a U-mode-only rule is denied on Supervisor mode. This ensures the Supervisor Memory Access Prevention (SMAP).
+
. A *Shared-Region* rule is enforced on both Supervisor and User modes, with restrictions depending on the `spmpcfg.S` and `spmpcfg.X` bits:
+
* If `spmpcfg.S` is not set, the region can be used for sharing data between S-mode and U-mode, yet not be executable. S-mode has RW permission to that region. U-mode has RW permission if `spmpcfg.X` is set, and it is restricted to read-only if `spmpcfg.X` is cleared.
+
* If `spmpcfg.S` is set, the region can be used for sharing code between S-mode and U-mode, yet not be writeable. S-mode has RX permission to that region. U-mode has RX permission if `spmpcfg.X` is set, and it is restricted to execute-only if `spmpcfg.X` is cleared.
+
. The encoding `spmpcfg.SRWX=1000` is reserved for future standard use.

The encoding and results are shown in the <<spmpencode>>:

[[spmpencode]]
image::SPMP_Encoding_Table_v6.svg[title="SPMP Encoding Table"]
// .SPMP Encoding Table.
// include::images/bytefield/spmpencode.adoc[]

**Deny**: Access fails.

**Enforce**: The R/W/X permissions are enforced on accesses.

**EnforceNoX**: The R/W permissions are enforced on accesses, while the X bit is forced to be zero.

**SHR**: It is shared between S/U modes with X, RX, RW, or ReadOnly privileges.

**RSVD**: It is reserved for future use.

**SUM bit**: The SPMP uses the `sstatus.SUM` (permit Supervisor User Memory access) bit to modify the privilege with which S-mode loads and stores access to physical memory. The semantics of `sstatus.SUM` in SPMP are consistent with those of the Machine-Level ISA (Please refer to the "Memory Privilege in mstatus Register" subsection in the riscv-privileged spec for detailed information).

=== Address Matching

The A field in an SPMP entry's configuration register encodes the address-matching mode of the associated SPMP address register.
It is the same as PMP/ePMP.

Please refer to the "Address Matching" subsection of PMP in the riscv-privileged spec for detailed information.


[NOTE]
====
Software may determine the SPMP granularity by writing zero to `spmp0cfg`, then writing all ones to `spmpaddr0`, then reading back `spmpaddr0`. If asciimath:[G] is the index of the least-significant bit set, the SPMP granularity is asciimath:[2^{G+2}]
====

=== Supervisor Security Configuration (sseccfg) CSR

*Supervisor Security Configuration (sseccfg)* is a new Supervisor mode CSR used for configuring SPMP features. 
All sseccfg fields defined on this proposal are WARL, and the remaining bits are reserved for future standard use and should always read zero.
This CSR has one field:

 - Bit 0. `sseccfg.SMAA` (Supervisor Memory Access Allowlist Policy): When set, this bit changes the default SPMP policy for S-Mode when accessing memory regions that don't have a matching rule to denied instead of ignored. This bit must reset to 0.

//  - Bit 1. `sseccfg.SMAL` (SPMP Match-Any Logic): When set, this bit changes the entry matching logic for SPMP from the default priority-based matching, where the lowest-numbered SPMP entry that matches any byte of the access determines the permissions for that access, to a match-any logic where the final permissions for the access are the union of the permissions of any entry that matches any byte of the access. This bit must reset to 0. If match-any logic is not implemented this bit should always read as zero.


For RV64 `sseccfg` is 64 bits wide, while for RV32 `sseccfg` is divided into `sseccfg` (lower 32 bits) and `sseccfgh` (upper 32 bits).

The `sseccfg` register must be cleared on reset. The presence of SPMP can be determined by probing the sseccfg CSR.

=== Matching Logic

// By default, when `sseccfg.SMAL` is clear:

* SPMP entries are statically prioritized, similar to PMP entries
+
* The lowest-numbered SPMP entry that matches any byte of access (indicated by an address and the accessed length) determines whether that access is allowed or denied
+
* The SPMP entry must match *all* bytes of access, or the access fails
+
* This matching is done irrespective of the S, R, W, and X bits

// When `sseccfg.SMAL` is set:

// * The union of permissions of any entries matching the access determines whether the access is allowed or denied
// +
// * All SPMP entries must match all bytes of the access, or the access fails
// +
// * This matching is done irrespective of the S, R, W, and X bits

On some implementations, misaligned loads, stores, and instruction fetches may also be decomposed into multiple accesses, some of which may succeed before an exception occurs. 
In particular, a portion of a misaligned store that passes the SPMP check may become visible, even if another portion fails the SPMP check. 
The same behavior may manifest for stores wider than XLEN bits (e.g., the FSD instruction in RV32D), even when the store address is naturally aligned.

1. If the effective privilege mode of the access is M, the access is `allowed`;
2. If the effective privilege mode of the access is S and no SPMP entry matches, if `sseccfg.SMAA` is clear the access is `allowed`, otherwise if `sseccfg.SMAA` is set, the access is denied;
3. If the effective privilege mode of the access is U and no SPMP entry matches, but at least one SPMP entry is implemented, the access is `denied`;
4. Otherwise, each access is checked according to the permission bits in the matching SPMP entry. That access is allowed if it satisfies the permission checking with the SRWX encoding corresponding to the access type.


[[spmp-and-paging]]
=== SPMP and Paging
The table below shows which mechanism to use. (Assume both paged virtual memory and SPMP are implemented.)

[cols="^1,^1", stripes=even, options="header"]
|===
|satp|Isolation mechanism
|satp.mode == Bare|SPMP only
|satp.mode != Bare|Paged Virtual Memory only
|===

SPMP and paged virtual memory cannot be active simultaneously for two reasons:

. An additional permission check layer would be introduced for each memory access.
+
. Sufficient protection is provided by paged virtual memory.

That means SPMP is enabled when `satp.mode==Bare` and SPMP is implemented.


[NOTE]
====
Please refer to Table "Encoding of satp MODE field" in the riscv-privileged spec for detailed information on the satp.MODE field.

// If page-based virtual memory is implemented, an `SFENCE.VMA` instruction with `rs1=x0` and `rs2=x0` is needed after writing the SPMP CSRs.
// If page-based virtual memory is not implemented, memory accesses check the SPMP settings synchronously, so no fence is needed.
// Please refer to hypervisor extension for additional synchronization requirements when hypervisor is implemented.
====

=== Exceptions
When an access fails, SPMP generates an exception based on the access type (i.e., load accesses, store/AMO accesses, and instruction fetches). Each exception has a different code.

The SPMP reuses page fault exception codes for SPMP faults since page faults are typically delegated to S-mode.
S-mode software (i.e., OS) can distinguish between SPMP and page faults by checking `satp.mode`, since SPMP and paged virtual memory cannot be active simultaneously (as described in <<spmp-and-paging>>).
*SPMP proposes to rename page fault to SPMP/page fault for clarity*.

Note that a single instruction may generate multiple accesses, which may not be mutually atomic. 

Table of renamed exception codes:

[cols="^1,^1,^1", stripes=even, options="header"]
|===
|Interrupt|Exception Code|Description
|0|12|Instruction SPMP/page fault
|0|13|Load SPMP/page fault
|0|15|Store/AMO SPMP/page fault
|===

[NOTE]
====
Please refer to Table "Supervisor cause register (scause) values after trap" in the riscv-privileged spec for detailed information on exception codes.
====

*Delegation*: Unlike PMP, which uses access faults for violations, SPMP uses SPMP/page faults for violations. The benefit of using SPMP/page faults is that the violations caused by SPMP can be delegated to S-mode, while the access violations caused by PMP can still be handled by machine mode.



=== Context Switching Optimization

Context switching with SPMP requires storing 64 address and 8 configuration registers (RV64), creating significant overhead. To optimize this:

* In RV32: two XLEN-bit read/write CSRs called `spmpswitch` and `spmpswitchh` are added, as depicted in <<spmpswitch-rv32>>.
* In RV64: one XLEN-bit read/write CSR called `spmpswitch` is added, as depicted in <<spmpswitch-rv64>>.

Each bit controls the activation of its corresponding SPMP entry. An entry is active only when both its `spmpswitch[i]` bit and `spmp[i]cfg.A` field are set, i.e., `spmpswitch[i] & spmp[i]cfg.A!=0`.

[[spmpswitch-rv32]]
.SPMP domain switch registers (`spmpswitch` and `spmpswitchh`), RV32.
include::images/bytefield/spmpswitch-rv32.adoc[]

[[spmpswitch-rv64]]
.SPMP domain switch register (`spmpswitch`), RV64.
include::images/bytefield/spmpswitch-rv64.adoc[]


[NOTE]
====
When `spmpswitch` is implemented and `spmpcfg[i].A == TOR`, an entry matches any address asciimath:[y] where:

- `spmpaddr[i-1]` asciimath:[\le y <] `spmpaddr[i]`
+
- This matching occurs regardless of `spmpcfg[i-1]` and `spmpswitch[i-1]` values

// If `spmpcfg[0].A == TOR`, zero is used for the lower bound, and so it matches any address y < spmpaddr[0].
====

The `spmpswitch` registers must be cleared on reset.


=== Access Methods of SPMP CSRs
How SPMP CSRs are accessed depends on whether the `Sscsrind` extension is implemented or not.

*Direct CSR access*: SPMP CSRs can be accessed directly with corresponding CSR numbers if the `Sscsrind` extension is not implemented.

*Indirect CSR access*: The SPMP supports indirect CSR access if the `Sscsrind` extension is implemented.
Each combination of `siselect` and `sireg` represents an access to the corresponding SPMP CSR.

[cols="^1,^2",stripes=even, options="header"]
|===
|`siselect` number|indirect CSR access of `sireg[i]`
|`siselect#1`|`sireg` -> `spmpcfg[0]`
// |`siselect#2`|`sireg` -> `spmpcfg[1]`
|    ...     |        ...
// |`siselect#15`|`sireg` -> `spmpcfg[14]`
|`siselect#16`|`sireg` -> `spmpcfg[15]`
|`siselect#17`|`sireg` -> `spmpaddr[0]`
// |`siselect#18`|`sireg` -> `spmpaddr[1]`
|    ...     |        ...
// |`siselect#79`|`sireg` -> `spmpaddr[62]`
|`siselect#80`|`sireg` -> `spmpaddr[63]`
|===

[NOTE]
====
The specific value of `siselect#1-80` will be allocated after review by the Arch Review Committee.

The rationale for SPMP only using the first `sireg` CSR is due to performance consideration.
If multiple `sireg` CSRs are assigned to each `siselect`, a jump table or additional calculations would be needed to determine which `sireg` to assess.
Assigning one `sireg` CSR for each `siselect` would be more efficient.

Please refer to the `Sscsrind` extension specification for details on indirect CSR accesses:
https://github.com/riscv/riscv-indirect-csr-access
====
