[[Summary_of_Hardware_Changes]]
== Summary of Hardware Changes

=== Sharing Registers and Comparators with PMP
Given that PMP and SPMP have similar layout of address/config registers and the same address matching logic.
Reusing registers and comparators between PMP and SPMP is benefitial to reduce hardware cost.

Implementations can consider PMP/SPMP (PMPs for short) entries as a resource pool.
A new M-mode CSR called `mpmpdeleg` is introduced to control which subset of the PMPs entries is delegated to S-mode (i.e., to be used as SPMP entries). 

Specificly, an implementation with 64 PMPs entries in total, by setting `mpmpdeleg` to 32 at runtime, the PMPs[0]-PMPs[31] is used as PMP entries, while PMPs[32]-PMPs[63] is used as SPMP entries.

An implementation can still have a fixed number of PMP and SPMP entries by hardwiring the `mpmpdeleg` to some constant.


[NOTE]
====
In the case where the Sscsrind extension is not implemented.
S-mode software sees SPMP[mpmpdeleg]-SPMP[max_PMPs_nums - 1].
This is because keeping the SPMP index starting at 0 adds extra overhead to the address decoding path.
====



=== New CSRs and Exception Code

[cols="^1,^2",stripes=even, options="header"]
|===
|Item|Changes
|CSR for delegating PMPs entries|1 new CSR
|CSRs for SPMP address|64 new CSRs
|CSRs for SPMP configuration|16 new CSRs for RV32 and 8 for RV64
|CSR for Domain switch|2 new CSRs for RV32 and 1 for RV64
|Renamed exception code|*_Instruction page fault_* renamed to *_Instruction SPMP/page fault_* +
*_Load page fault_* renamed to *_Load SPMP/page fault_* +
*_Store/AMO page fault_* renamed to *_Store/AMO SPMP/page fault_*
|===
